ad:
  security:
    defaultToken: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE1OTU0NDQzNzYsInVzZXJfdXVpZCI6IjdmMGQ3YTg4LTFlNmEtNGE5YS05MmRhLTA4NGNkMDNlZjE3NiIsImVudmlyb25tZW50X3V1aWQiOiI2YWQxMjgzYy01MDlhLTExZTktODUzYS0wMjJmZWJmY2Q5NzAiLCJwcm9qZWN0X3V1aWQiOiI0MGIwOWNhZi04NjMzLTRkMzItYTk3NS0yZmYxZDY5NjM3NTIiLCJ2ZXJzaW9uX3V1aWQiOiJjZjIzMWFkNy01MDlhLTExZTktODUzYS0wMjJmZWJmY2Q5NzAiLCJ0ZW5hbnRfaWQiOiJwdWJsaWMiLCJzdWIiOiJ7XCJ1c2VySWRcIjpcIjdmMGQ3YTg4LTFlNmEtNGE5YS05MmRhLTA4NGNkMDNlZjE3NlwiLFwiYWNjb3VudE5vbkV4cGlyZWRcIjp0cnVlLFwiYWNjb3VudE5vbkxvY2tlZFwiOnRydWUsXCJjcmVkZW50aWFsc05vbkV4cGlyZWRcIjp0cnVlLFwiZW5hYmxlZFwiOnRydWUsIFwidGVuYW50X2lkXCI6IFwicHVibGljXCJ9In0.u83w_ThqPrYwznj74KGt6nQ8By_ZnmQ384e_DdohcGEKUvfmMyrMSBHCRJAexLhVL-pv3RyeUyoEFc0jNVdA-Q
server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
spring:
  application:
    name: gc-support-merchandising
  datasource:
    hikari:
      idleTimeout: 210000
      max-lifetime: 270000
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        jdbc:
            batch_size: 30
            order_inserts: true
            order_updates: true
            
  profiles:
    active: dev
  messages:
    basename: i18n/messages

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    app:
      name: '@project.name@'
      description: '@project.description@'
      version: @project.version@
      encoding: @project.build.sourceEncoding@
      java:
        version: @java.version@


